name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - pip
  - pip:
      - wandb
      - seaborn
      - pandas
      - pandas-profiling
      - ydata-profiling
      - pyarrow