name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cookiecutter
  - hydra-core
  - git
  - ipython
  - notebook
  - jupyterlab
  - pip
  - pip:
      - wandb
      - mlflow
      - matplotlib
      - pandas
