name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.2.2
  - scikit-learn=0.24.1
  - pip=20.3.3
  - pip:
      - wandb
      - matplotlib
      - pillow
      - pandas
